[package]
name = "day-10"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
utils = { git = "https://github.com/Kanjirito/advent-of-code.git", rev = "utils-v0.7.0", version = "0.6.0" }
